[package]
name = "x"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.1"
serde = { version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"
hyper = "1.5.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.11.0", features = ["serde", "v4"]}
